# Goal: To deploy the built and tested image to an EC2 instance

name: CD

on:
    workflow_call:
        
#code checkout, build and run the docker image on the EC2 instance
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Run docker container
              run: docker compose up -d

              