name: CICD Demo

on: 
 push:


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        run: echo " code clone"
        
        
  build:
   needs: code
   runs-on: ubuntu-latest
   steps:
      - name: build the code
        run: echo " code build"
        
  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo " code tests done"

  deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo " code is deploy"     
