# Goal: To run the Continous Integration (CI/CD) for this project

name: continous intergration
on:
  workflow_dispatch:


jobs:
  #Code lint and test
  code-lint:
    uses: ./.github/workflows/lint_and_test.yml
  #Build and push docker image

  build-and-push:
    secrets: inherit
    needs: code-lint
    uses: ./.github/workflows/docker.yml  

    #deploy the docker image to an EC2 instance
  deploy:
    secrets: inherit
    needs: build-and-push
    uses: ./.github/workflows/cd.yml