# Goal is to call the workflows in the order to implement shift left

name: devsecops_pipeline
on:
  push:

jobs:

  #secrets scanning for any exposed tokens, keys, or passwords
  secrets-scanning:
    uses: ./.github/workflows/secrets-scanning.yml
    secrets: inherit
    
  #Code lint and test

  code-lint:
    needs: secrets-scanning
    uses: ./.github/workflows/lint_and_test.yml

# SAST scan for static code analysis and code related issues using sonar qube
  sast:
    needs: code-lint
    uses: ./.github/workflows/sonar_scan.yml
    secrets: inherit

  #dependency-scan
  dependency-scan:
    needs: sast
    uses: ./.github/workflows/dependency_scan.yml
    
#Build and scan docker image

   # Build & Scan
  build-and-scan:
        secrets: inherit
        needs: dependency-scan
        uses: ./.github/workflows/trivy_scans.yml

  #deploy the docker image to an EC2 instance
  #deploy:
    #secrets: inherit
   # needs: build-and-push
   # uses: ./.github/workflows/cd.yml