# Goal: To check if the python code is syntactically correct

name: lint code

on:
  push:


jobs:
     code-linter:
        runs-on: ubuntu-latest
        steps:
           - name: code checkout
             uses: actions/checkout@v7

           - name: setup python
             uses: actions/setup-python@v4
             with:
                python-version: '3.13'

           - name: install dependencies
             run: pip install -r requirements.txt     

           - name: code lint
             run: ruff check .

           - name: code test
             run: pytest
               