# Goal : To scan the code for tokens, secrets, API Keys, or any leaked Passwords so that
# if found, we can quickly rotate the exposed tokens/keys/etc

name: secrets-scanning

#reusable workflow for scanning secrets in the codebase
on:
  workflow_call:

jobs:
  secrets-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          #from very fist commit pull all the code

      - name: sacn for leaks
        uses: dortort/betterleaks-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

